<div class="card">
    <h3><b>Tabulasi</b></h3>
    <div class="card-body table-responsive border rounded" style="padding: 0.5rem 1rem;">
        <table id="table1" class="table table-hover table-bordered table-responsive display" style="width:100%">
            <thead>
                <tr>
                    <th scope="col" rowspan="3" colspan="2">KLB</th>
                    <th scope="col" colspan="6">Jenis Industri Pariwisata</th>
                    
                    <th scope="col" rowspan="2">Jumlah</th>
                    <th scope="col" rowspan="2">Sampel</th>
                </tr>
                <tr>
                	<th scope="col" >Penyediaan jasa akomodasi bagi wisatawan</th>
                    <th scope="col" >Penyediaan jasa makan dan minum</th>
                    <th scope="col" >Penyediaan jasa angkutan darat untuk penumpang</th>
                    <th scope="col" >Penyediaan jasa kebudayaan, olahraga dan rekreasi</th>
                    <th scope="col" >Aktivitas perdagangan barang-barang pariwisata</th>
                    <th scope="col" >Jenis Industri Lainnya</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" rowspan="3">Hubungan dengan KRT</th>
                </tr>
                <tr>
                    <td>KRT</td>
                    <td>10.58</td>
                    <td>21.53</td>
                    <td>20.80</td>
                    <td>19.71</td>
                    <td>16.06</td>
                    <td>11.31</td>
                    <td>100.00</td>
                    <td>39.03</td>
                </tr>
                <tr>
                    <td>Bukan KRT</td>
                    <td>10.75</td>
                    <td>38.55</td>
                    <td>5.37</td>
                    <td>13.32</td>
                    <td>24.07</td>
                    <td>7.94</td>
                    <td>100.00</td>
                    <td>60.97</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="13">Umur</th>
                </tr>
                <tr>
                    <td>< 15</td>
                    <td>0.00</td>
                    <td>50.00</td>
                    <td>0.00</td>
                    <td>50.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>0.28</td>
                </tr>
                <tr>
                    <td>15-19</td>
                    <td>4.35</td>
                    <td>50.00</td>
                    <td>0.00</td>
                    <td>26.09</td>
                    <td>19.57</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>6.55</td>
                </tr>
                <tr>
                    <td>20-24</td>
                    <td>12.80</td>
                    <td>36.80</td>
                    <td>3.20</td>
                    <td>16.80</td>
                    <td>22.40</td>
                    <td>8.00</td>
                    <td>100.00</td>
                    <td>17.81</td>
                </tr>
                <tr>
                    <td>25-29</td>
                    <td>10.81</td>
                    <td>27.93</td>
                    <td>10.81</td>
                    <td>13.51</td>
                    <td>20.72</td>
                    <td>16.22</td>
                    <td>100.00</td>
                    <td>15.81</td>
                </tr>
                <tr>
                    <td>30-34</td>
                    <td>12.68</td>
                    <td>26.76</td>
                    <td>12.68</td>
                    <td>11.27</td>
                    <td>23.94</td>
                    <td>12.68</td>
                    <td>100.00</td>
                    <td>10.11</td>
                </tr>
                <tr>
                    <td>35-39</td>
                    <td>11.27</td>
                    <td>25.35</td>
                    <td>14.08</td>
                    <td>14.08</td>
                    <td>22.54</td>
                    <td>12.68</td>
                    <td>100.00</td>
                    <td>10.11</td>
                </tr>
                <tr>
                    <td>40-44</td>
                    <td>6.35</td>
                    <td>26.98</td>
                    <td>17.46</td>
                    <td>22.22</td>
                    <td>14.29</td>
                    <td>12.70</td>
                    <td>100.00</td>
                    <td>8.97</td>
                </tr>
                <tr>
                    <td>45-49</td>
                    <td>6.67</td>
                    <td>26.67</td>
                    <td>16.67</td>
                    <td>25.00</td>
                    <td>23.33</td>
                    <td>1.67</td>
                    <td>100.00</td>
                    <td>8.55</td>
                </tr>
                <tr>
                    <td>50-54</td>
                    <td>16.13</td>
                    <td>38.71</td>
                    <td>12.90</td>
                    <td>8.06</td>
                    <td>14.52</td>
                    <td>9.68</td>
                    <td>100.00</td>
                    <td>8.83</td>
                </tr>
                <tr>
                    <td>55-59</td>
                    <td>6.25</td>
                    <td>50.00</td>
                    <td>6.25</td>
                    <td>12.50</td>
                    <td>21.88</td>
                    <td>3.13</td>
                    <td>100.00</td>
                    <td>4.56</td>
                </tr>
                <tr>
                    <td>60-64</td>
                    <td>0.00</td>
                    <td>28.57</td>
                    <td>28.57</td>
                    <td>3.57</td>
                    <td>35.71</td>
                    <td>3.57</td>
                    <td>100.00</td>
                    <td>3.99</td>
                </tr>
                <tr>
                    <td>65+</td>
                    <td>25.81</td>
                    <td>16.13</td>
                    <td>19.35</td>
                    <td>16.13</td>
                    <td>16.13</td>
                    <td>6.45</td>
                    <td>10.00</td>
                    <td>4.42</td>
                </tr>
                <tr>
                    <th scope="row" rowspan= "6">Usia</th>
                </tr>
                <tr>
                    <td>Under 15 dan 15-24</td>
                    <td>10.40</td>
                    <td>40.46</td>
                    <td>2.31</td>
                    <td>19.65</td>
                    <td>21.39</td>
                    <td>5.78</td>
                    <td>100.00</td>
                    <td>24.64</td>
                </tr>
                <tr>
                    <td>25-34</td>
                    <td>11.54</td>
                    <td>27.47</td>
                    <td>11.54</td>
                    <td>12.64</td>
                    <td>21.98</td>
                    <td>14.84</td>
                    <td>100.00</td>
                    <td>25.93</td>
                </tr>
                <tr>
                    <td>35-44</td>
                    <td>8.96</td>
                    <td>26.12</td>
                    <td>15.67</td>
                    <td>17.92</td>
                    <td>18.66</td>
                    <td>12.69</td>
                    <td>100.00</td>
                    <td>19.09</td>
                </tr>
                <tr>
                    <td>55-64</td>
                    <td>3.33</td>
                    <td>40.00</td>
                    <td>16.67</td>
                    <td>8.33</td>
                    <td>28.33</td>
                    <td>3.33</td>
                    <td>100.00</td>
                    <td>8.55</td>
                </tr>
                <tr>
                    <td>65+</td>
                    <td>25.81</td>
                    <td>16.13</td>
                    <td>19.35</td>
                    <td>16.13</td>
                    <td>16.13</td>
                    <td>6.45</td>
                    <td>100.00</td>
                    <td>4.42</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Status Perkawinan</th>
                </tr>
                <tr>
                    <td>Belum Kawin</td>
                    <td>10.22</td>
                    <td>37.63</td>
                    <td>6.99</td>
                    <td>16.67</td>
                    <td>20.97</td>
                    <td>7.53</td>
                    <td>100.00</td>
                    <td>26.50</td>
                </tr>
                <tr>
                    <td>Pernah Kawin</td>
                    <td>10.85</td>
                    <td>29.84</td>
                    <td>12.98</td>
                    <td>15.50</td>
                    <td>20.93</td>
                    <td>9.88</td>
                    <td>100.00</td>
                    <td>73.50</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Jenis Kelamin</th>
                </tr>
                <tr>
                    <td>Laki-laki</td>
                    <td>10.74</td>
                    <td>24.82</td>
                    <td>18.38</td>
                    <td>19.09</td>
                    <td>15.99</td>
                    <td>10.98</td>
                    <td>100.00</td>
                    <td>56.69</td>
                <tr>
                    <td>Perempuan</td>
                    <td>10.60</td>
                    <td>42.40</td>
                    <td>1.06</td>
                    <td>10.95</td>
                    <td>28.27</td>
                    <td>6.71</td>
                    <td>100.00</td>
                    <td>40.31</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="5">Jumlah Pendapatan</th>
                </tr>
                    <td>< Rp1.500.000</td>
                    <td>12.56</td>
                    <td>39.07</td>
                    <td>9.30</td>
                    <td>12.56</td>
                    <td>17.21</td>
                    <td>9.30</td>
                    <td>100.00</td>
                    <td>30.63</td>
                <tr>
                    <td>Rp1.500.000-Rp2.500.000</td>
                    <td>8.77</td>
                    <td>33.33</td>
                    <td>10.96</td>
                    <td>18.86</td>
                    <td>19.30</td>
                    <td>8.77</td>
                    <td>100.00</td>
                    <td>32.48</td>
                </tr>
                <tr>
                    <td>Rp2.500.000-Rp3.500.000</td>
                    <td>12.71</td>
                    <td>19.49</td>
                    <td>13.56</td>
                    <td>20.34</td>
                    <td>25.42</td>
                    <td>8.47</td>
                    <td>100.00</td>
                    <td>16.81</td>
                </tr>
                <tr>
                    <td>>Rp3.500.000</td>
                    <td>9.22</td>
                    <td>29.08</td>
                    <td>13.48</td>
                    <td>12.06</td>
                    <td>25.53</td>
                    <td>10.64</td>
                    <td>100.00</td>
                    <td>20.09</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Tempat Bekerja Menggunakan Internet</th>
                </tr>
                    <td>Ya</td>
                    <td>13.62</td>
                    <td>25.53</td>
                    <td>14.26</td>
                    <td>20.21</td>
                    <td>14.89</td>
                    <td>11.49</td>
                    <td>100.00</td>
                    <td>66.95</td>
                <tr>
                    <td>Tidak</td>
                    <td>33.19</td>
                    <td>44.83</td>
                    <td>5.60</td>
                    <td>6.90</td>
                    <td>33.19</td>
                    <td>4.74</td>
                    <td>100.00</td>
                    <td>33.05</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Promosi</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>14.55</td>
                    <td>23.81</td>
                    <td>14.29</td>
                    <td>23.28</td>
                    <td>12.70</td>
                    <td>11.38</td>
                    <td>100.00</td>
                    <td>53.85</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9.78</td>
                    <td>32.61</td>
                    <td>14.13</td>
                    <td>7.61</td>
                    <td>23.91</td>
                    <td>11.96</td>
                    <td>100.00</td>
                    <td>13.11</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>4.74</td>
                    <td>44.83</td>
                    <td>5.60</td>
                    <td>6.90</td>
                    <td>33.19</td>
                    <td>4.74</td>
                    <td>100.00</td>
                    <td>33.05</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Komunikasi</th>
                </tr>
                    <td>Ya</td>
                    <td>13.73</td>
                    <td>25.49</td>
                    <td>14.60</td>
                    <td>20.26</td>
                    <td>14.38</td>
                    <td>11.55</td>
                    <td>100.00</td>
                    <td>65.38</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9.09</td>
                    <td>27.27</td>
                    <td>0.00</td>
                    <td>18.18</td>
                    <td>36.36</td>
                    <td>9.09</td>
                    <td>100.00</td>
                    <td>1.57</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>4.74</td>
                    <td>44.83</td>
                    <td>5.60</td>
                    <td>6.90</td>
                    <td>33.19</td>
                    <td>4.74</td>
                    <td>100.00</td>
                    <td>33.05</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Transaksi</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>15.34</td>
                    <td>22.71</td>
                    <td>15.04</td>
                    <td>19.76</td>
                    <td>15.34</td>
                    <td>11.80</td>
                    <td>100.00</td>
                    <td>48.29</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9.16</td>
                    <td>32.82</td>
                    <td>12.21</td>
                    <td>21.37</td>
                    <td>13.74</td>
                    <td>10.69</td>
                    <td>100.00</td>
                    <td>18.66</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>4.74</td>
                    <td>44.83</td>
                    <td>5.60</td>
                    <td>6.90</td>
                    <td>33.19</td>
                    <td>4.74</td>
                    <td>100.00</td>
                    <td>33.05</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Keinginan untuk Menambah Pekerjaan</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>8.04</td>
                    <td>26.22</td>
                    <td>16.43</td>
                    <td>18.18</td>
                    <td>19.23</td>
                    <td>11.89</td>
                    <td>100.00</td>
                    <td>40.74</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>12.50</td>
                    <td>35.82</td>
                    <td>7.93</td>
                    <td>14.18</td>
                    <td>22.12</td>
                    <td>7.45</td>
                    <td>100.00</td>
                    <td>59.26</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Pekerjaan Utama</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>9.86</td>
                    <td>32.75</td>
                    <td>10.81</td>
                    <td>15.90</td>
                    <td>22.10</td>
                    <td>8.59</td>
                    <td>100.00</td>
                    <td>89.60</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>17.81</td>
                    <td>24.66</td>
                    <td>16.44</td>
                    <td>15.07</td>
                    <td>10.96</td>
                    <td>15.07</td>
                    <td>100.00</td>
                    <td>10.40</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Lama Bekerja</th>
                </tr>
                <tr>
                    <td><=36 bulan</td>
                    <td>10.38</td>
                    <td>38.75</td>
                    <td>5.88</td>
                    <td>17.30</td>
                    <td>19.72</td>
                    <td>7.96</td>
                    <td>100.00</td>
                    <td>41.17</td>
                </tr>
                <tr>
                    <td>>36 bulan</td>
                    <td>10.90</td>
                    <td>27.12</td>
                    <td>15.25</td>
                    <td>14.77</td>
                    <td>21.79</td>
                    <td>10.17</td>
                    <td>100.00</td>
                    <td>58.83</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Kepunyaan Pekerjaan Sebelumnya</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>9.30</td>
                    <td>35.66</td>
                    <td>6.20</td>
                    <td>17.05</td>
                    <td>22.48</td>
                    <td>9.30</td>
                    <td>100.00</td>
                    <td>18.38</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>10.99</td>
                    <td>31.06</td>
                    <td>12.57</td>
                    <td>15.53</td>
                    <td>20.59</td>
                    <td>9.25</td>
                    <td>100.00</td>
                    <td>81.62</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Kepunyaan Pekerjaan di Sektor Pariwisata Sebelumnya</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>9.52</td>
                    <td>35.71</td>
                    <td>0.00</td>
                    <td>19.05</td>
                    <td>21.43</td>
                    <td>14.29</td>
                    <td>100.00</td>
                    <td>5.98</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>10.76</td>
                    <td>31.67</td>
                    <td>12.12</td>
                    <td>15.61</td>
                    <td>20.91</td>
                    <td>8.94</td>
                    <td>100.00</td>
                    <td>94.02</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Memiliki Pekerjaan Lainnya (<i>Multiple Jobs</i>)</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>14.22</td>
                    <td>24.17</td>
                    <td>13.27</td>
                    <td>18.48</td>
                    <td>14.69</td>
                    <td>15.17</td>
                    <td>100.00</td>
                    <td>30.06</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9.16</td>
                    <td>35.23</td>
                    <td>10.59</td>
                    <td>14.66</td>
                    <td>23.63</td>
                    <td>6.72</td>
                    <td>100.00</td>
                    <td>69.94</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Memiliki Pekerjaan Lainnya (<i>Multiple Jobs</i>) berdasarkan Jenis Kelamin</th>
                </tr>
                <tr>
                    <td>Laki-laki</td>
                    <td>11.80</td>
                    <td>18.63</td>
                    <td>16.77</td>
                    <td>22.36</td>
                    <td>13.04</td>
                    <td>17.39</td>
                    <td>100.00</td>
                    <td>76.30</td>
                </tr>
                <tr>
                    <td>Perempuan</td>
                    <td>22.00</td>
                    <td>42.00</td>
                    <td>2.00</td>
                    <td>6.00</td>
                    <td>20.00</td>
                    <td>8.00</td>
                    <td>100.00</td>
                    <td>23.70</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Pendapatan Sampingan Lebih Besar daripadda Pendapatan Utama</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>10.17</td>
                    <td>25.42</td>
                    <td>16.95</td>
                    <td>20.34</td>
                    <td>11.86</td>
                    <td>15.25</td>
                    <td>100.00</td>
                    <td>27.96</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>15.79</td>
                    <td>23.68</td>
                    <td>11.84</td>
                    <td>17.76</td>
                    <td>15.79</td>
                    <td>15.13</td>
                    <td>100.00</td>
                    <td>72.04</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="10">Pendidikan Tinggi yang Ditamatkan</th>
                </tr>
                <tr>
                    <td>Tidak/Belum Pernah Sekolah</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>0.60</td>
                </tr>
                <tr>
                    <td>Tidak/Belum SD</td>
                    <td>25.00</td>
                    <td>25.00</td>
                    <td>25.00</td>
                    <td>0.00</td>
                    <td>25.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>2.41</td>
                </tr>
                <tr>
                    <td>SD/MI/SDLB/Paket A</td>
                    <td>10.34</td>
                    <td>24.14</td>
                    <td>17.24</td>
                    <td>31.03</td>
                    <td>13.79</td>
                    <td>3.45</td>
                    <td>100.00</td>
                    <td>17.47</td>
                </tr>
                <tr>
                    <td>SMP/MTs/SMPLB/Paket B</td>
                    <td>4.76</td>
                    <td>38.10</td>
                    <td>11.90</td>
                    <td>28.57</td>
                    <td>11.90</td>
                    <td>4.76</td>
                    <td>100.00</td>
                    <td>25.30</td>
                </tr>
                <tr>
                    <td>SMA/MA/SMALB/Paket C</td>
                    <td>11.11</td>
                    <td>20.00</td>
                    <td>22.22</td>
                    <td>22.22</td>
                    <td>17.78</td>
                    <td>6.67</td>
                    <td>100.00</td>
                    <td>27.11</td>
                </tr>
                <tr>
                    <td>SMK/MAK</td>
                    <td>19.35</td>
                    <td>48.39</td>
                    <td>9.68</td>
                    <td>12.90</td>
                    <td>9.68</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>18.67</td>
                </tr>
                <tr>
                    <td>Diploma I/II/III</td>
                    <td>25.00</td>
                    <td>25.00</td>
                    <td>0.00</td>
                    <td>25.00</td>
                    <td>12.50</td>
                    <td>12.50</td>
                    <td>100.00</td>
                    <td>4.82</td>
                </tr>
                <tr>
                    <td>Diploma IV</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>100.00</td>
                    <td>0.60</td>
                </tr>
                <tr>
                    <td>S1/S2/S3</td>
                    <td>0.00</td>
                    <td>20.00</td>
                    <td>20.00</td>
                    <td>40.00</td>
                    <td>0.00</td>
                    <td>20.00</td>
                    <td>100.00</td>
                    <td>3.01</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="8">Pendidikan Tertinggi</th>
                </tr>
                <tr>
                    <td>Tidak Bersekolah</td>
                    <td>20.00</td>
                    <td>20.00</td>
                    <td>40.00</td>
                    <td>0.00</td>
                    <td>20.00</td>
                    <td>0.00</td>
                    <td>100.00</td>
                    <td>3.01</td>
                </tr>
                <tr>
                    <td>Sekolah Dasar</td>
                    <td>10.34</td>
                    <td>24.14</td>
                    <td>17.24</td>
                    <td>31.03</td>
                    <td>13.79</td>
                    <td>3.45</td>
                    <td>100.00</td>
                    <td>17.47</td>
                </tr>
                <tr>
                    <td>Sekolah Menengah Pertama</td>
                    <td>4.76</td>
                    <td>38.10</td>
                    <td>11.90</td>
                    <td>28.57</td>
                    <td>11.90</td>
                    <td>4.76</td>
                    <td>100.00</td>
                    <td>25.30</td>
                </tr>
                <tr>
                    <td>Sekolah Menengah Atas</td>
                    <td>11.11</td>
                    <td>20.00</td>
                    <td>22.22</td>
                    <td>22.22</td>
                    <td>17.78</td>
                    <td>6.67</td>
                    <td>100.00</td>
                    <td>27.11</td>
                </tr>
                <tr>
                    <td>Diploma (Diploma I, II, III)</td>
                    <td>25.00</td>
                    <td>25.00</td>
                    <td>0.00</td>
                    <td>25.00</td>
                    <td>12.50</td>
                    <td>12.50</td>
                    <td>100.00</td>
                    <td>4.82</td>
                </tr>
                <tr>
                    <td>Sarjana (Diploma IV dan Strata I)</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>100.00</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Pascasarjana (Strata II dan III)</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>100.00</td>
                    <td></td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Pendidikan Tertinggi</th>
                </tr>
                <tr>
                    <td>Di Bawah SMA/SMK</td>
                    <td>7.89</td>
                    <td>31.58</td>
                    <td>15.79</td>
                    <td>27.63</td>
                    <td>13.16</td>
                    <td>3.95</td>
                    <td>100.00</td>
                    <td>45.78</td>
                </tr>
                <tr>
                    <td>SMA/SMK</td>
                    <td>14.47</td>
                    <td>31.58</td>
                    <td>17.11</td>
                    <td>18.42</td>
                    <td>14.47</td>
                    <td>3.95</td>
                    <td>100.00</td>
                    <td>45.78</td>
                </tr>
                <tr>
                    <td>Di Atas SMA/SMK</td>
                    <td>14.29</td>
                    <td>21.43</td>
                    <td>7.14</td>
                    <td>28.57</td>
                    <td>7.14</td>
                    <td>21.43</td>
                    <td>100.00</td>
                    <td>8.43</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Keikutsertaan dalam Pelatihan</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>18.26</td>
                    <td>30.43</td>
                    <td>11.30</td>
                    <td>19.13</td>
                    <td>10.43</td>
                    <td>10.43</td>
                    <td>100.00</td>
                    <td>16.38</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9.20</td>
                    <td>32.20</td>
                    <td>11.41</td>
                    <td>15.16</td>
                    <td>23.00</td>
                    <td>9.03</td>
                    <td>100.00</td>
                    <td>83.62</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Penggunaan Bahasa Asing di Tempat Kerja</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>17.81</td>
                    <td>27.40</td>
                    <td>15.75</td>
                    <td>13.70</td>
                    <td>13.01</td>
                    <td>12.33</td>
                    <td>100.00</td>
                    <td>20.80</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>8.81</td>
                    <td>33.09</td>
                    <td>10.25</td>
                    <td>16.37</td>
                    <td>23.02</td>
                    <td>8.45</td>
                    <td>100.00</td>
                    <td>79.20</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Rumah Layak Huni</th>
                </tr>
                <tr>
                    <td>Layak Huni</td>
                    <td>14.80</td>
                    <td>34.53</td>
                    <td>10.31</td>
                    <td>18.39</td>
                    <td>14.35</td>
                    <td>7.62</td>
                    <td>100.00</td>
                    <td>31.77</td>
                </tr>
                <tr>
                    <td>Tidak Layak Huni</td>
                    <td>8.77</td>
                    <td>30.69</td>
                    <td>11.90</td>
                    <td>14.61</td>
                    <td>24.01</td>
                    <td>10.02</td>
                    <td>100.00</td>
                    <td>68.23</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Sumber Air Minum Bersih dan Akses Air Minum Layak</th>
                </tr>
                <tr>
                    <td>Sumber air minum bersih</td>
                    <td>10.42</td>
                    <td>32.29</td>
                    <td>11.31</td>
                    <td>16.22</td>
                    <td>21.28</td>
                    <td>8.48</td>
                    <td>100.00</td>
                    <td>39.17</td>
                </tr>
                <tr>
                    <td>Akses air minum layak</td>
                    <td>13.82</td>
                    <td>34.18</td>
                    <td>11.64</td>
                    <td>17.09</td>
                    <td>15.27</td>
                    <td>8.00</td>
                    <td>100.00</td>
                    <td>39.17</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Sanitasi Layak</th>
                </tr>
                <tr>
                    <td>Sanitasi Layak</td>
                    <td>11.53</td>
                    <td>32.36</td>
                    <td>10.50</td>
                    <td>17.56</td>
                    <td>19.10</td>
                    <td>8.95</td>
                    <td>100.00</td>
                    <td>82.76</td>
                </tr>
                <tr>
                    <td>Sanitasi Tidak Layak</td>
                    <td>6.61</td>
                    <td>29.75</td>
                    <td>15.70</td>
                    <td>7.44</td>
                    <td>29.75</td>
                    <td>10.74</td>
                    <td>100.00</td>
                    <td>17.24</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>