<div class="card">
    <h3><b>Tabulasi</b></h3>
    <div class="card-body table-responsive border rounded" style="padding: 0.5rem 1rem;">
        <table id="table1" class="table table-hover table-bordered table-responsive display" style="width:100%">
            <thead>
                <tr>
                    <th scope="col" rowspan="2" colspan="2">KLB</th>
                    <th scope="col" colspan="12">Jenis Industri Pariwisata</th>
                    
                    <th scope="col" rowspan="2" colspan="2">Jumlah</th>
                    <th scope="col" rowspan="2" colspan="2">Sampel</th>
                </tr>
                <tr>
                	<th scope="col" colspan="2">Penyediaan jasa akomodasi bagi wisatawan</th>
                    <th scope="col" colspan="2">Penyediaan jasa makan dan minum</th>
                    <th scope="col" colspan="2">Penyediaan jasa angkutan darat untuk penumpang</th>
                    <th scope="col" colspan="2">Penyediaan jasa kebudayaan, olahraga dan rekreasi</th>
                    <th scope="col" colspan="2">Aktivitas perdagangan barang-barang pariwisata</th>
                    <th scope="col" colspan="2">Jenis Industri Lainnya</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" rowspan="3">Hubungan dengan KRT</th>
                </tr>
                <tr>
                    <td>KRT</td>
                    <td>29</td>
                    <td>10.58%</td>
                    <td>59</td>
                    <td>21.53%</td>
                    <td>57</td>
                    <td>20.80%</td>
                    <td>54</td>
                    <td>19.71%</td>
                    <td>44</td>
                    <td>16.06%</td>
                    <td>31</td>
                    <td>11.31%</td>
                    <td>274</td>
                    <td>100.00%</td>
                    <td>274</td>
                    <td>39.03%</td>
                </tr>
                <tr>
                    <td>Bukan KRT</td>
                    <td>46</td>
                    <td>10.75%</td>
                    <td>165</td>
                    <td>38.55%</td>
                    <td>23</td>
                    <td>5.37%</td>
                    <td>57</td>
                    <td>13.32%</td>
                    <td>103</td>
                    <td>24.07%</td>
                    <td>34</td>
                    <td>7.94%</td>
                    <td>428</td>
                    <td>100.00%</td>
                    <td>428</td>
                    <td>60.97%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="13">Umur</th>
                </tr>
                <tr>
                    <td>< 15</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>1</td>
                    <td>50.00%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>1</td>
                    <td>50.00%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>2</td>
                    <td>100.00%</td>
                    <td>2</td>
                    <td>0.28%</td>
                </tr>
                <tr>
                    <td>15-19</td>
                    <td>2</td>
                    <td>4.35%</td>
                    <td>23</td>
                    <td>50.00%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>12</td>
                    <td>26.09%</td>
                    <td>9</td>
                    <td>19.57%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>46</td>
                    <td>100.00%</td>
                    <td>46</td>
                    <td>6.55%</td>
                </tr>
                <tr>
                    <td>20-24</td>
                    <td>16</td>
                    <td>12.80%</td>
                    <td>46</td>
                    <td>36.80%</td>
                    <td>4</td>
                    <td>3.20%</td>
                    <td>21</td>
                    <td>16.80%</td>
                    <td>28</td>
                    <td>22.40%</td>
                    <td>10</td>
                    <td>8.00%</td>
                    <td>125</td>
                    <td>100.00%</td>
                    <td>125</td>
                    <td>17.81%</td>
                </tr>
                <tr>
                    <td>25-29</td>
                    <td>12</td>
                    <td>10.81%</td>
                    <td>31</td>
                    <td>27.93%</td>
                    <td>12</td>
                    <td>10.81%</td>
                    <td>15</td>
                    <td>13.51%</td>
                    <td>23</td>
                    <td>20.72%</td>
                    <td>18</td>
                    <td>16.22%</td>
                    <td>111</td>
                    <td>100.00%</td>
                    <td>111</td>
                    <td>15.81%</td>
                </tr>
                <tr>
                    <td>30-34</td>
                    <td>9</td>
                    <td>12.68%</td>
                    <td>19</td>
                    <td>26.76%</td>
                    <td>9</td>
                    <td>12.68%</td>
                    <td>8</td>
                    <td>11.27%</td>
                    <td>17</td>
                    <td>23.94%</td>
                    <td>9</td>
                    <td>12.68%</td>
                    <td>71</td>
                    <td>100.00%</td>
                    <td>71</td>
                    <td>10.11%</td>
                </tr>
                <tr>
                    <td>35-39</td>
                    <td>8</td>
                    <td>11.27%</td>
                    <td>18</td>
                    <td>25.35%</td>
                    <td>10</td>
                    <td>14.08%</td>
                    <td>10</td>
                    <td>14.08%</td>
                    <td>16</td>
                    <td>22.54%</td>
                    <td>9</td>
                    <td>12.68%</td>
                    <td>71</td>
                    <td>100.00%</td>
                    <td>71</td>
                    <td>10.11%</td>
                </tr>
                <tr>
                    <td>40-44</td>
                    <td>4</td>
                    <td>6.35%</td>
                    <td>17</td>
                    <td>26.98%</td>
                    <td>11</td>
                    <td>17.46%</td>
                    <td>14</td>
                    <td>22.22%</td>
                    <td>9</td>
                    <td>14.29%</td>
                    <td>8</td>
                    <td>12.70%</td>
                    <td>63</td>
                    <td>100.00%</td>
                    <td>63</td>
                    <td>8.97%</td>
                </tr>
                <tr>
                    <td>45-49</td>
                    <td>4</td>
                    <td>6.67%</td>
                    <td>16</td>
                    <td>26.67%</td>
                    <td>10</td>
                    <td>16.67%</td>
                    <td>15</td>
                    <td>25.00%</td>
                    <td>14</td>
                    <td>23.33%</td>
                    <td>1</td>
                    <td>1.67%</td>
                    <td>60</td>
                    <td>100.00%</td>
                    <td>60</td>
                    <td>8.55%</td>
                </tr>
                <tr>
                    <td>50-54</td>
                    <td>10</td>
                    <td>16.13%</td>
                    <td>24</td>
                    <td>38.71%</td>
                    <td>8</td>
                    <td>12.90%</td>
                    <td>5</td>
                    <td>8.06%</td>
                    <td>9</td>
                    <td>14.52%</td>
                    <td>6</td>
                    <td>9.68%</td>
                    <td>62</td>
                    <td>100.00%</td>
                    <td>62</td>
                    <td>8.83%</td>
                </tr>
                <tr>
                    <td>55-59%</td>
                    <td>2</td>
                    <td>6.25%</td>
                    <td>16</td>
                    <td>50.00%</td>
                    <td>2</td>
                    <td>6.25%</td>
                    <td>4</td>
                    <td>12.50%</td>
                    <td>7</td>
                    <td>21.88%</td>
                    <td>1</td>
                    <td>3.13%</td>
                    <td>32</td>
                    <td>100.00%</td>
                    <td>32</td>
                    <td>4.56%</td>
                </tr>
                <tr>
                    <td>60-64</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>8</td>
                    <td>28.57%</td>
                    <td>8</td>
                    <td>28.57%</td>
                    <td>1</td>
                    <td>3.57%</td>
                    <td>10</td>
                    <td>35.71%</td>
                    <td>1</td>
                    <td>3.57%</td>
                    <td>28</td>
                    <td>100.00%</td>
                    <td>28</td>
                    <td>3.99%</td>
                </tr>
                <tr>
                    <td>65+</td>
                    <td>8</td>
                    <td>25.81%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>6</td>
                    <td>19.35%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>2</td>
                    <td>6.45%</td>
                    <td>31</td>
                    <td>10.00%</td>
                    <td>31</td>
                    <td>4.42%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan= "6">Usia</th>
                </tr>
                <tr>
                    <td>Under 15 dan 15-24</td>
                    <td>18</td>
                    <td>10.40%</td>
                    <td>70</td>
                    <td>40.46%</td>
                    <td>4</td>
                    <td>2.31%</td>
                    <td>34</td>
                    <td>19.65%</td>
                    <td>37</td>
                    <td>21.39%</td>
                    <td>10</td>
                    <td>5.78%</td>
                    <td>173</td>
                    <td>100.00%</td>
                    <td>173</td>
                    <td>24.64%</td>
                </tr>
                <tr>
                    <td>25-34</td>
                    <td>21</td>
                    <td>11.54%</td>
                    <td>50</td>
                    <td>27.47%</td>
                    <td>21</td>
                    <td>11.54%</td>
                    <td>23</td>
                    <td>12.64%</td>
                    <td>40</td>
                    <td>21.98%</td>
                    <td>27</td>
                    <td>14.84%</td>
                    <td>182</td>
                    <td>100.00%</td>
                    <td>182</td>
                    <td>25.93%</td>
                </tr>
                <tr>
                    <td>35-44</td>
                    <td>12</td>
                    <td>8.96</td>
                    <td>35</td>
                    <td>26.12%</td>
                    <td>21</td>
                    <td>15.67%</td>
                    <td>24</td>
                    <td>17.92%</td>
                    <td>25</td>
                    <td>18.66%</td>
                    <td>17</td>
                    <td>12.69%</td>
                    <td>134</td>
                    <td>100.00%</td>
                    <td>134</td>
                    <td>19.09%</td>
                </tr>
                <tr>
                    <td>55-64</td>
                    <td>2</td>
                    <td>3.33%</td>
                    <td>24</td>
                    <td>40.00%</td>
                    <td>10</td>
                    <td>16.67%</td>
                    <td>5</td>
                    <td>8.33%</td>
                    <td>17</td>
                    <td>28.33%</td>
                    <td>2</td>
                    <td>3.33%</td>
                    <td>60</td>
                    <td>100.00%</td>
                    <td>60</td>
                    <td>8.55%</td>
                </tr>
                <tr>
                    <td>65+</td>
                    <td>8</td>
                    <td>25.81%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>6</td>
                    <td>19.35%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>5</td>
                    <td>16.13%</td>
                    <td>2</td>
                    <td>6.45%</td>
                    <td>31</td>
                    <td>100.00%</td>
                    <td>31</td>
                    <td>4.42%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Status Perkawinan</th>
                </tr>
                <tr>
                    <td>Belum Kawin</td>
                    <td>19</td>
                    <td>10.22%</td>
                    <td>70</td>
                    <td>37.63%</td>
                    <td>13</td>
                    <td>6.99%</td>
                    <td>31</td>
                    <td>16.67%</td>
                    <td>39</td>
                    <td>20.97%</td>
                    <td>14</td>
                    <td>7.53%</td>
                    <td>186</td>
                    <td>100.00%</td>
                    <td>186</td>
                    <td>26.50%</td>
                </tr>
                <tr>
                    <td>Pernah Kawin</td>
                    <td>56</td>
                    <td>10.85%</td>
                    <td>154</td>
                    <td>29.84%</td>
                    <td>67</td>
                    <td>12.98%</td>
                    <td>80</td>
                    <td>15.50%</td>
                    <td>108</td>
                    <td>20.93%</td>
                    <td>51</td>
                    <td>9.88%</td>
                    <td>516</td>
                    <td>100.00%</td>
                    <td>516</td>
                    <td>73.50%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Jenis Kelamin</th>
                </tr>
                <tr>
                    <td>Laki-laki</td>
                    <td>45</td>
                    <td>10.74%</td>
                    <td>104</td>
                    <td>24.82%</td>
                    <td>77</td>
                    <td>18.38%</td>
                    <td>80</td>
                    <td>19.09%</td>
                    <td>67</td>
                    <td>15.99%</td>
                    <td>46</td>
                    <td>10.98%</td>
                    <td>419</td>
                    <td>100.00%</td>
                    <td>419</td>
                    <td>56.69%</td>
                <tr>
                    <td>Perempuan</td>
                    <td>30</td>
                    <td>10.60%</td>
                    <td>120</td>
                    <td>42.40%</td>
                    <td>3</td>
                    <td>1.06%</td>
                    <td>31</td>
                    <td>10.95%</td>
                    <td>80</td>
                    <td>28.27%</td>
                    <td>19</td>
                    <td>6.71%</td>
                    <td>283</td>
                    <td>100.00%</td>
                    <td>283</td>
                    <td>40.31%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="5">Jumlah Pendapatan</th>
                </tr>
                    <td>< Rp1.500.000</td>
                    <td>27</td>
                    <td>12.56%</td>
                    <td>84</td>
                    <td>39.07%</td>
                    <td>20</td>
                    <td>9.30%</td>
                    <td>27</td>
                    <td>12.56%</td>
                    <td>37</td>
                    <td>17.21%</td>
                    <td>20</td>
                    <td>9.30%</td>
                    <td>215</td>
                    <td>100.00%</td>
                    <td>215</td>
                    <td>30.63%</td>
                <tr>
                    <td>Rp1.500.000-Rp2.500.000</td>
                    <td>20</td>
                    <td>8.77%</td>
                    <td>76</td>
                    <td>33.33%</td>
                    <td>25</td>
                    <td>10.96%</td>
                    <td>43</td>
                    <td>18.86%</td>
                    <td>44</td>
                    <td>19.30%</td>
                    <td>20</td>
                    <td>8.77%</td>
                    <td>228</td>
                    <td>100.00%</td>
                    <td>228</td>
                    <td>32.48%</td>
                </tr>
                <tr>
                    <td>Rp2.500.000-Rp3.500.000</td>
                    <td>15</td>
                    <td>12.71%</td>
                    <td>23</td>
                    <td>19.49%</td>
                    <td>16</td>
                    <td>13.56%</td>
                    <td>24</td>
                    <td>20.34%</td>
                    <td>30</td>
                    <td>25.42%</td>
                    <td>10</td>
                    <td>8.47%</td>
                    <td>118</td>
                    <td>100%</td>
                    <td>118</td>
                    <td>16.81%</td>
                </tr>
                <tr>
                    <td>>Rp3.500.000</td>
                    <td>13</td>
                    <td>9.22%</td>
                    <td>41</td>
                    <td>29.08%</td>
                    <td>19</td>
                    <td>13.48%</td>
                    <td>17</td>
                    <td>12.06%</td>
                    <td>36</td>
                    <td>25.53%</td>
                    <td>15</td>
                    <td>10.64%</td>
                    <td>141</td>
                    <td>100.00%</td>
                    <td>141</td>
                    <td>20.09%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="3">Tempat Bekerja Menggunakan Internet</th>
                </tr>
                    <td>Ya</td>
                    <td>64</td>
                    <td>13.62%</td>
                    <td>120</td>
                    <td>25.53%</td>
                    <td>67</td>
                    <td>14.26%</td>
                    <td>95</td>
                    <td>20.21%</td>
                    <td>70</td>
                    <td>14.89%</td>
                    <td>54</td>
                    <td>11.49%</td>
                    <td>470</td>
                    <td>100.00%</td>
                    <td>470</td>
                    <td>66.95%</td>
                <tr>
                    <td>Tidak</td>
                    <td>77</td>
                    <td>33.19%</td>
                    <td>104</td>
                    <td>44.83%</td>
                    <td>13</td>
                    <td>5.60%</td>
                    <td>16</td>
                    <td>6.90%</td>
                    <td>77</td>
                    <td>33.19%</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>232</td>
                    <td>100.00%</td>
                    <td>232</td>
                    <td>100.00%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Promosi</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>55</td>
                    <td>14.55%</td>
                    <td>90</td>
                    <td>23.81%</td>
                    <td>54</td>
                    <td>14.29%</td>
                    <td>88</td>
                    <td>23.28%</td>
                    <td>48</td>
                    <td>12.70%</td>
                    <td>43</td>
                    <td>11.38%</td>
                    <td>378</td>
                    <td>100.00%</td>
                    <td>378</td>
                    <td>53.85%</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>9</td>
                    <td>9.78%</td>
                    <td>30</td>
                    <td>32.61%</td>
                    <td>13</td>
                    <td>14.13%</td>
                    <td>7</td>
                    <td>7.61%</td>
                    <td>22</td>
                    <td>23.91%</td>
                    <td>11</td>
                    <td>11.96</td>
                    <td>92</td>
                    <td>100.00%</td>
                    <td>92</td>
                    <td>13.11%</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>11</td>
                    <td>4.74%%</td>
                    <td>104</td>
                    <td>44.83%</td>
                    <td>13</td>
                    <td>5.60%</td>
                    <td>16</td>
                    <td>6.90%</td>
                    <td>77</td>
                    <td>33.19%</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>232</td>
                    <td>100.00%</td>
                    <td>232</td>
                    <td>100.00%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Komunikasi</th>
                </tr>
                    <td>Ya</td>
                    <td>63</td>
                    <td>13.73%</td>
                    <td>117</td>
                    <td>25.49%</td>
                    <td>67</td>
                    <td>14.60%</td>
                    <td>93</td>
                    <td>20.26%</td>
                    <td>66</td>
                    <td>14.38%</td>
                    <td>53</td>
                    <td>11.55%</td>
                    <td>459</td>
                    <td>100.00%</td>
                    <td>459</td>
                    <td>65.38%</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>1</td>
                    <td>9.09%</td>
                    <td>3</td>
                    <td>27.27%</td>
                    <td>0</td>
                    <td>0.00%</td>
                    <td>2</td>
                    <td>18.18%</td>
                    <td>4</td>
                    <td>36.36%</td>
                    <td>1</td>
                    <td>9.09%</td>
                    <td>11</td>
                    <td>100.00%</td>
                    <td>11</td>
                    <td>1.57%</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>104</td>
                    <td>44.83%</td>
                    <td>13</td>
                    <td>5.60%</td>
                    <td>16</td>
                    <td>6.90%</td>
                    <td>77</td>
                    <td>33.19%</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>232</td>
                    <td>100.00%</td>
                    <td>232</td>
                    <td>33.05%</td>
                </tr>
                <tr>
                    <th scope="row" rowspan="4">Tempat Bekerja Menggunakan Internet untuk Transaksi</th>
                </tr>
                <tr>
                    <td>Ya</td>
                    <td>52</td>
                    <td>15.34%</td>
                    <td>77</td>
                    <td>22.71%</td>
                    <td>51</td>
                    <td>15.04%</td>
                    <td>67</td>
                    <td>19.76%</td>
                    <td>52</td>
                    <td>15.34%</td>
                    <td>40</td>
                    <td>11.80%</td>
                    <td>339</td>
                    <td>100.00%</td>
                    <td>339</td>
                    <td>48.29%</td>
                </tr>
                <tr>
                    <td>Tidak</td>
                    <td>12</td>
                    <td>9.16%</td>
                    <td>43</td>
                    <td>32.82%</td>
                    <td>16</td>
                    <td>12.21%</td>
                    <td>28</td>
                    <td>21.37%</td>
                    <td>18</td>
                    <td>13.74%</td>
                    <td>14</td>
                    <td>10.69%</td>
                    <td>131</td>
                    <td>100.00%</td>
                    <td>131</td>
                    <td>18.66%</td>
                </tr>
                <tr>
                    <td>Tidak Menggunakan Internet</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>104</td>
                    <td>44.83%</td>
                    <td>13</td>
                    <td>5.60%</td>
                    <td>16</td>
                    <td>6.90%</td>
                    <td>77</td>
                    <td>33.19%</td>
                    <td>11</td>
                    <td>4.74%</td>
                    <td>232</td>
                    <td>100%</td>
                    <td>232</td>
                    <td>33.05%</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>