<?= $this->extend('pvd/layout/dasbor/template'); ?>

<?= $this->section('content'); ?>

<header class="section-header">
  <h6 style="color: #4b395f;"><strong>Kesiapan Pemanfaatan TIK Unit Usaha Pariwisata Skala Mikro dan Kecil di Kota Batu dalam Menerapkan
      <i>Smart Tourism Destination</i></strong>
  </h6>
</header>
<hr class="hrjudul">

<div class="card">
  <div class="card-header">
    <strong>Tabulasi Unit Usaha Pariwisata Berdasarkan Perangkat Digital yang Dimiliki</strong>
    <!-- <button type="button" class="tombol btn-for text-right me-1 mt-1 justify-content-end align-item-end" data-bs-toggle="modal" data-bs-target="#exampleModal4-doughnut">
                            <i class="fa-solid fa-download"></i>
   </button> -->
  </div>
  <div class="card-body table-responsive" style="padding: 0.5rem 1rem;">
    <!-- style="padding:0px 0px 0px 0px;" -->
    <!-- <blockquote class="blockquote mb-0"> -->
    <table class="table table-hover table-bordered table-responsive" style="width:100%">
      <thead style="color: #fff;  font-weight:bold; text-align:center;">
      <tr>
        <th rowspan="3">Kecamatan</th>
        <th rowspan="3">Desa/Kelurahan</th>
        <th colspan="12">Jenis Unit Usaha Pariwisata</th>
        <th rowspan="3">Total</th>
      </tr>
      <tr>
        <th colspan="4">Jasa Transportasi Wisata</th>
        <th colspan="4">Jasa Penyediaan Makanan dan Minuman</th>
        <th colspan="4">Penyediaan Akomodasi</th>
      </tr>
      <tr>
        <th>PC</th>
        <th>Laptop</th>
        <th>Tablet</th>
        <th>Smartphone</th>
        <th>PC</th>
        <th>Laptop</th>
        <th>Tablet</th>
        <th>Smartphone</th>        
        <th>PC</th>
        <th>Laptop</th>
        <th>Tablet</th>
        <th>Smartphone</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td rowspan="8">Batu</td>
        <td>Oro-oro Ombo</td>
        <td>0</td>
        <td>4</td>
        <td>0</td>
        <td>21</td>
        <td>0</td>
        <td>4</td>
        <td>4</td>
        <td>52</td>
        <td>0</td>
        <td>7</td>
        <td>0</td>
        <td>38</td>
        <td>130</td>    
      </tr>
      <tr>
        <td>Temas</td>
        <td>0</td>
        <td>2</td>
        <td>1</td>
        <td>24</td>
        <td>2</td>
        <td>13</td>
        <td>1</td>
        <td>137</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>6</td>
        <td>188</td>    
      </tr>
      <tr>
        <td>Sisir</td>
        <td>0</td>
        <td>3</td>
        <td>1</td>
        <td>37</td>
        <td>7</td>
        <td>7</td>
        <td>4</td>
        <td>230</td>
        <td>1</td>
        <td>3</td>
        <td>0</td>
        <td>30</td>
        <td>323</td>    
      </tr>
      <tr>
        <td>Ngaglik</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>20</td>
        <td>11</td>
        <td>26</td>
        <td>8</td>
        <td>118</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>8</td>
        <td>194</td>    
      </tr>
      <tr>
        <td>Pesanggrahan</td>
        <td>0</td>
        <td>4</td>
        <td>0</td>
        <td>15</td>
        <td>1</td>
        <td>4</td>
        <td>0</td>
        <td>56</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>3</td>
        <td>83</td>    
      </tr>
      <tr>
        <td>Songgokerto</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>3</td>
        <td>0</td>
        <td>26</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>46</td>
        <td>79</td>    
      </tr>
      <tr>
        <td>Sumberejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>15</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>4</td>
        <td>22</td>    
      </tr>
      <tr>
        <td>Sidomulyo</td>
        <td>1</td>
        <td>2</td>
        <td>0</td>
        <td>6</td>
        <td>2</td>
        <td>3</td>
        <td>0</td>
        <td>46</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>62</td>    
      </tr>
      <tr>
        <td rowspan="7">Junrejo</td>
        <td>Tlekung</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr>
        <td>Junrejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>20</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>20</td>    
      </tr>
      <tr>
        <td>Mojorejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>4</td>
        <td>1</td>
        <td>2</td>
        <td>0</td>
        <td>11</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>18</td>    
      </tr>
      <tr>
        <td>Torongrejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>9</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>12</td>    
      </tr>
      <tr>
        <td>Beji</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>9</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>31</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>4</td>
        <td>49</td>    
      </tr>
      <tr>
        <td>Pendem</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>29</td>
        <td>0</td>
        <td>7</td>
        <td>0</td>
        <td>67</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>105</td>    
      </tr>
      <tr>
        <td>Dadaprejo</td>
        <td>1</td>
        <td>1</td>
        <td>0</td>
        <td>5</td>
        <td>0</td>
        <td>3</td>
        <td>0</td>
        <td>28</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>38</td>    
      </tr>
      <tr>
        <td rowspan="9">Bumiaji</td>
        <td>Pandarejo</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>8</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>45</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>57</td>    
      </tr>
      <tr>
        <td>Bumiaji</td>
        <td>0</td>
        <td>2</td>
        <td>1</td>
        <td>10</td>
        <td>1</td>
        <td>2</td>
        <td>1</td>
        <td>14</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>31</td>    
      </tr>
      <tr>
        <td>Bulukerto</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>1</td>
        <td>0</td>
        <td>8</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>10</td>    
      </tr>
      <tr>
        <td>Gunungsari</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>3</td>
        <td>0</td>
        <td>18</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>21</td>    
      </tr>
      <tr>
        <td>Punten</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>4</td>
        <td>2</td>
        <td>5</td>
        <td>1</td>
        <td>21</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>4</td>
        <td>38</td>    
      </tr>
      <tr>
        <td>Tulungrejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>13</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>13</td>    
      </tr>
      <tr>
        <td>Sumbergondo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr>
        <td>Giripurno</td>
        <td>3</td>
        <td>0</td>
        <td>0</td>
        <td>7</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>12</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>23</td>    
      </tr>
      <tr>
        <td>Sumber Brantas</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr style="font-weight: bold;">
        <td colspan=2 class="text-center">Total</td>
        <td>7</td>
        <td>25</td>
        <td>3</td>
        <td>204</td>
        <td>29</td>
        <td>89</td>
        <td>19</td>
        <td>977</td>
        <td>1</td>
        <td>15</td>
        <td>1</td>
        <td>146</td> 
        <td>1516</td> 
      </tr>
      </tbody>
    </table>
    </div>
</div>

<?= $this->endSection(); ?>