<?= $this->extend('pvd/layout/dasbor/template'); ?>

<?= $this->section('content'); ?>

<header class="section-header">
  <h6 style="color: #4b395f;"><strong>Kesiapan Pemanfaatan TIK Unit Usaha Pariwisata Skala Mikro dan Kecil di Kota Batu dalam Menerapkan
      <i>Smart Tourism Destination</i></strong>
  </h6>
</header>
<hr class="hrjudul">

<div class="card">
  <div class="card-header">
    <strong>Tabulasi Unit Usaha Pariwisata Berdasarkan Upaya untuk Mengikuti Perkembangan Isu Ekonomi Terkini</strong>
    <!-- <button type="button" class="tombol btn-for text-right me-1 mt-1 justify-content-end align-item-end" data-bs-toggle="modal" data-bs-target="#exampleModal4-doughnut">
                            <i class="fa-solid fa-download"></i>
   </button> -->
  </div>
  <div class="card-body table-responsive" style="padding: 0.5rem 1rem;">
    <!-- style="padding:0px 0px 0px 0px;" -->
    <!-- <blockquote class="blockquote mb-0"> -->
    <table class="table table-hover table-bordered table-responsive" style="width:100%">
      <thead style="color: #fff;  font-weight:bold; text-align:center;">
        <tr>
          <th rowspan="3">Kecamatan</th>
          <th rowspan="3">Desa/Kelurahan</th>
          <th colspan="12">Jenis Unit Usaha Pariwisata</th>
          <th rowspan="3">Total</th>
        </tr>
        <tr>
          <th colspan="4">Jasa Transportasi Wisata</th>
          <th colspan="4">Jasa Penyediaan Makanan dan Minuman</th>
          <th colspan="4">Penyediaan Akomodasi</th>
        </tr>
        <tr>
          <th>[1]</th>
          <th>[2]</th>
          <th>[3]</th>
          <th>[4]</th>
          <th>[1]</th>
          <th>[2]</th>
          <th>[3]</th>
          <th>[4]</th>
          <th>[1]</th>
          <th>[2]</th>
          <th>[3]</th>
          <th>[4]</th>
        </tr>
      </thead>
      <tbody>
      <tr>
        <td rowspan="8">Batu</td>
        <td>Oro-oro Ombo</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>1</td>
        <td>7</td>
        <td>8</td>
        <td>20</td>
        <td>8</td>
        <td>2</td>
        <td>3</td>
        <td>15</td>
        <td>3</td>
        <td>79</td>    
      </tr>
      <tr>
        <td>Temas</td>
        <td>4</td>
        <td>4</td>
        <td>8</td>
        <td>1</td>
        <td>3</td>
        <td>19</td>
        <td>43</td>
        <td>14</td>
        <td>0</td>
        <td>0</td>
        <td>3</td>
        <td>1</td>
        <td>100</td>    
      </tr>
      <tr>
        <td>Sisir</td>
        <td>5</td>
        <td>6</td>
        <td>19</td>
        <td>6</td>
        <td>23</td>
        <td>35</td>
        <td>56</td>
        <td>23</td>
        <td>0</td>
        <td>5</td>
        <td>6</td>
        <td>2</td>
        <td>186</td>    
      </tr>
      <tr>
        <td>Ngaglik</td>
        <td>1</td>
        <td>4</td>
        <td>9</td>
        <td>2</td>
        <td>9</td>
        <td>23</td>
        <td>51</td>
        <td>18</td>
        <td>1</td>
        <td>0</td>
        <td>3</td>
        <td>0</td>
        <td>121</td>    
      </tr>
      <tr>
        <td>Pesanggrahan</td>
        <td>1</td>
        <td>2</td>
        <td>7</td>
        <td>2</td>
        <td>2</td>
        <td>8</td>
        <td>23</td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>51</td>    
      </tr>
      <tr>
        <td>Songgokerto</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>4</td>
        <td>12</td>
        <td>1</td>
        <td>2</td>
        <td>0</td>
        <td>12</td>
        <td>8</td>
        <td>42</td>    
      </tr>
      <tr>
        <td>Sumberejo</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>3</td>
        <td>2</td>
        <td>11</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>1</td>
        <td>20</td>    
      </tr>
      <tr>
        <td>Sidomulyo</td>
        <td>0</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>1</td>
        <td>5</td>
        <td>12</td>
        <td>5</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>30</td>    
      </tr>
      <tr>
        <td rowspan="7">Junrejo</td>
        <td>Tlekung</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr>
        <td>Junrejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>2</td>
        <td>8</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>14</td>    
      </tr>
      <tr>
        <td>Mojorejo</td>
        <td>0</td>
        <td>1</td>
        <td>2</td>
        <td>0</td>
        <td>2</td>
        <td>4</td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>14</td>    
      </tr>
      <tr>
        <td>Torongrejo</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>3</td>
        <td>3</td>
        <td>2</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>11</td>    
      </tr>
      <tr>
        <td>Beji</td>
        <td>0</td>
        <td>5</td>
        <td>2</td>
        <td>2</td>
        <td>0</td>
        <td>6</td>
        <td>20</td>
        <td>3</td>
        <td>0</td>
        <td>1</td>
        <td>1</td>
        <td>0</td>
        <td>40</td>    
      </tr>
      <tr>
        <td>Pendem</td>
        <td>2</td>
        <td>2</td>
        <td>17</td>
        <td>1</td>
        <td>7</td>
        <td>9</td>
        <td>32</td>
        <td>9</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>79</td>    
      </tr>
      <tr>
        <td>Dadaprejo</td>
        <td>0</td>
        <td>0</td>
        <td>3</td>
        <td>1</td>
        <td>1</td>
        <td>4</td>
        <td>16</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>26</td>    
      </tr>
      <tr>
        <td rowspan="9">Bumiaji</td>
        <td>Pandanrejo</td>
        <td>0</td>
        <td>2</td>
        <td>4</td>
        <td>1</td>
        <td>4</td>
        <td>7</td>
        <td>18</td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>42</td>    
      </tr>
      <tr>
        <td>Bumiaji</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>1</td>
        <td>4</td>
        <td>7</td>
        <td>18</td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>42</td>    
      </tr>
      <tr>
        <td>Bulukerto</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
        <td>3</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>4</td>    
      </tr>
      <tr>
        <td>Gunungsari</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>2</td>
        <td>0</td>
        <td>5</td>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>8</td>    
      </tr>
      <tr>
        <td>Punten</td>
        <td>0</td>
        <td>1</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>7</td>
        <td>6</td>
        <td>0</td>
        <td>1</td>
        <td>0</td>
        <td>1</td>
        <td>26</td>    
      </tr>
      <tr>
        <td>Tulungrejo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>4</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>6</td>    
      </tr>
      <tr>
        <td>Sumbergondo</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr>
        <td>Giripurno</td>
        <td>0</td>
        <td>2</td>
        <td>4</td>
        <td>2</td>
        <td>0</td>
        <td>4</td>
        <td>4</td>
        <td>2</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>18</td>    
      </tr>
      <tr>
        <td>Sumber Brantas</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>    
      </tr>
      <tr style="font-weight: bold;">
        <td colspan=2 class="text-center">Total</td>
        <td>17</td>
        <td>34</td>
        <td>88</td>
        <td>25</td>
        <td>74</td>
        <td>153</td>
        <td>351</td>
        <td>107</td>
        <td>5</td>
        <td>12</td>
        <td>42</td>
        <td>17</td> 
        <td>925</td> 
      </tr>
      </tbody>
    </table>
    </div>
    <div class="card-body" style="padding: 0.5rem 1rem;">
      <p>
        Keterangan:<br>	
        [1]	Sangat Tidak Mengikuti<br>
        [2]	Tidak Mengikuti<br>
        [3]	Mengikuti<br>
        [4]	Sangat Mengikuti<br>
      </p>
    </div>
</div>

<?= $this->endSection(); ?>

